export default [
  {
    id: 1,
    username: "johndoe",
    password: "12345",
    firstName: "John",
    lastName: "Doe",
    handle: "@johndoe",
    profilePicture: "../../images/emily.webp",
    bannerPicture: "../../images/emily-banner.jpeg",
    bio: "Love the fresh produce, unique goods, and sense of community that I find there.",
    location: "Los Angeles, CA",
    dateOfBirth: "10/12/1993",
    dateJoined: "March 2018",
    followingCount: 123,
    followersCount: 10,
    editing: false,
    role: "CONSUMER",
  },
  {
    id: 2,
    username: "janedoe",
    password: "12345",
    firstName: "Jane",
    lastName: "Doe",
    handle: "@janedoe",
    profilePicture: "../../images/emily.webp",
    bannerPicture: "../../images/emily-banner.jpeg",
    bio: "Love the fresh produce, unique goods, and sense of community that I find there.",
    location: "Los Angeles, CA",
    dateOfBirth: "10/12/1993",
    dateJoined: "March 2018",
    followingCount: 123,
    followersCount: 10,
    editing: false,
    role: "CONSUMER",
  },
  {
    id: 3,
    username: "ecofarm",
    password: "12345",
    businessName: "Eco Farm",
    handle: "@ecofarm",
    profilePicture: "../../images/emily.webp",
    bannerPicture: "../../images/emily-banner.jpeg",
    bio: "We grow our produce in a sustainable way and we are proud to be able to provide our community with fresh and organic produce.",
    location: "Los Angeles, CA",
    dateOfBirth: "10/12/1993",
    dateJoined: "March 2018",
    followingCount: 123,
    followersCount: 10,
    editing: false,
    role: "FARMER",
  },
  {
    id: 4,
    username: "yuezhao",
    password: "12345",
    firstName: "Yue",
    lastName: "Zhao",
    handle: "@yuezhao",
    profilePicture: "../../images/emily.webp",
    bannerPicture: "../../images/emily-banner.jpeg",
    bio: "We grow our produce in a sustainable way and we are proud to be able to provide our community with fresh and organic produce.",
    location: "Seattle, WA",
    dateOfBirth: "10/12/1993",
    dateJoined: "March 2018",
    followingCount: 123,
    followersCount: 10,
    editing: false,
    role: "ADMIN",
  },
];
